<template>
  <div>
    <h2 class="font-semibold mb-2 text-xl">Mechanical Production duties:</h2>
    <ul class="list-disc list-outside">
      <li>Ensure that the CNC machines and machine room are clean, in proper state of operating at all times;</li>
      <li>Operate all CNC machines;</li>
      <li>Fabricate parts from Aluminum, steel and other exotic alloys;</li>
      <li>Consign the actual fabrication times and stock weights in the appropriate log;</li>
      <li>Verify parts tolerances and mechanical assembly clearances;</li>
      <li>Verify general part surface quality;</li>
      <li>Log machine hours and machine problems on the machine log;</li>
      <li>Establish and follow up on interval maintenance programs;</li>
      <li>Verify cutters stock, cutters condition.</li>
    </ul>

    <h2 class="font-semibold pt-4 mb-2 text-xl">Programming duties:</h2>
    <ul class="list-disc list-outside">
      <li>Read and analyze the CAD generated by the design engineer;</li>
      <li>Assist the programmer in generating tool path;</li>
      <li>Assist in noting machining times and stock weights in the appropriate system to generate cost sheets;</li>
      <li>Verify versus actual times and stock weight and generate a warning in case of discrepancies.</li>
    </ul>
  </div>
</template>

<script lang="ts" setup>

</script>

<style>

</style>